# Generated by Django 3.0.4 on 2020-05-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='LastName', max_length=100),
            preserve_default=False,
        ),
    ]
