# Generated by Django 3.0.4 on 2020-05-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_reader_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='otherfield',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
