# Generated by Django 3.0.4 on 2020-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reader_otherfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='otherfield',
            field=models.CharField(max_length=20),
        ),
    ]
