# Generated by Django 3.0.4 on 2020-05-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200522_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='otherfield',
            new_name='age',
        ),
    ]
