# Generated by Django 3.0.6 on 2020-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200524_0047'),
        ('transactions', '0002_auto_20200524_1947'),
        ('users', '0005_auto_20200522_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='books_bought',
            field=models.ManyToManyField(through='transactions.Transaction', to='books.Book'),
        ),
    ]
