# Generated by Django 3.0.6 on 2020-05-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200524_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
