# Generated by Django 3.0.6 on 2020-05-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200524_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={},
        ),
        migrations.RemoveField(
            model_name='reader',
            name='books_bought',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='reader',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reader',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reader',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
