# Generated by Django 3.0.4 on 2020-05-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField()),
                ('has_account', models.BooleanField(default=False)),
                ('account_linked', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Reader')),
            ],
        ),
    ]
