# Generated by Django 3.0.6 on 2020-05-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
