# Generated by Django 3.0.4 on 2020-06-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_auto_20200531_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
