# Generated by Django 3.0.6 on 2020-05-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateField()),
                ('author', models.ForeignKey(default='Anon', on_delete=models.SET('NO AUTHOR'), related_name='books_written', to='authors.Author')),
                ('publisher', models.ForeignKey(on_delete=models.SET('NO PUBLISHER'), related_name='books_published', to='publishers.Publisher')),
            ],
        ),
    ]
