# Generated by Django 3.0.4 on 2020-05-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
        ('authors', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateField()),
                ('author', models.ForeignKey(default=0, on_delete=models.SET('NO AUTHOR'), related_name='books_written', to='authors.Author')),
                ('publisher', models.ForeignKey(on_delete=models.SET('NO PUBLISHER'), related_name='books_published', to='publishers.Publisher')),
                ('tags', models.ManyToManyField(null=True, related_name='books', to='tags.Tag')),
            ],
        ),
    ]
