# Generated by Django 3.0.6 on 2020-05-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200524_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=5),
            preserve_default=False,
        ),
    ]
