# Generated by Django 3.0.4 on 2020-05-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('books', '0002_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='books', to='tags.Tag'),
        ),
    ]
