# Generated by Django 3.0.6 on 2020-05-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200525_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bought_by',
        ),
    ]
