# Generated by Django 3.0.6 on 2020-05-25 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20200525_1150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publishers', '0001_initial'),
        ('authors', '0001_initial'),
        ('books', '0007_remove_book_bought_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bought_by',
            field=models.ManyToManyField(through='transactions.Transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='books_written', to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='books_published', to='publishers.Publisher'),
        ),
    ]
