# Generated by Django 3.0.6 on 2020-05-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20200525_1617'),
        ('books', '0008_auto_20200525_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='informations',
            field=models.ManyToManyField(through='information.Information', to='books.Book'),
        ),
    ]
