# Generated by Django 3.0.6 on 2020-05-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_informations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='informations',
            new_name='information',
        ),
    ]
