# Generated by Django 3.0.6 on 2020-05-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200525_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='information',
        ),
    ]
