# Generated by Django 3.0.4 on 2020-05-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_author_pic'),
        ('books', '0014_auto_20200531_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='books_written', to='authors.Author'),
        ),
    ]
