# Generated by Django 3.0.4 on 2020-06-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200531_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_content',
            field=models.FileField(blank=True, null=True, upload_to='contents'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
