# Generated by Django 3.0.4 on 2020-05-17 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_name'),
        ('books', '0002_book_tags'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.CharField(default='Empty', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to='users.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_taken', to='books.Book'),
        ),
    ]
