# Generated by Django 3.0.6 on 2020-05-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200525_1137'),
        ('transactions', '0006_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='books',
        ),
        migrations.AddField(
            model_name='transaction',
            name='books',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_involved', to='books.Book'),
            preserve_default=False,
        ),
    ]
