# Generated by Django 3.0.6 on 2020-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_bought_by'),
        ('transactions', '0007_auto_20200525_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='books',
        ),
        migrations.AddField(
            model_name='transaction',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
