# Generated by Django 3.0.6 on 2020-05-25 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200525_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0008_auto_20200525_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='books',
        ),
        migrations.AddField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_involved', to='books.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_made',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
