# Generated by Django 3.0.4 on 2020-05-22 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('book', models.ForeignKey(default=0, on_delete=models.SET('NO BOOK AVAILABLE'), related_name='reviews_starred', to='books.Book')),
                ('reviewer', models.ForeignKey(on_delete=models.SET('NO AUTHOR'), related_name='reviews_written', to='users.Reader')),
            ],
        ),
    ]
