# Generated by Django 3.0.4 on 2020-06-03 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20200602_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
