# Generated by Django 3.0.4 on 2020-06-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_pic',
            field=models.ImageField(blank=True, null=True, upload_to='publishers/%Y/%m'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
